version: '3.1'

services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  mariadb:
    image: mariadb
    hostname: mariadb
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: shop@1996
  shop-ui:
    image: node:10.18.1-alpine
    ports:
    - 3000:3000
    - 9010:9010
    volumes:
    - "${PWD}/shop-ui:/shop-ui"
    working_dir: /shop-ui
    command: bash -c "npm install && npm start"
  shop-goods:
    image: maven:3.6.3-openjdk-11-slim
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - mariadb
    volumes:
    - "${PWD}/shop-service:/dubbo-shop/shop-service"
    - mvn-cache:/root/.m2/repository
    working_dir: /dubbo-shop/shop-service
    command: bash -c "mvn install -DskipTests && cd shop-user && mvn spring-boot:run"

volumes:
  mvn-cache: